### ISSUE TITLE
Website Peer Review

### ISSUE THREAD

**Issue by smcdermott3** [avenigalla32/Project#3]
Bugs:
1) The nav bar links don't always work on every page.
2) The CSS of the homepage is different than that of the others.

Content:
1) There is a typo upon entering first page: "Which Jordan is your faorite?"
2) Resize photos

I like the concept of the website and the start of it. The photos you got on the home page are cool and all match. I also like the grid of it.

**Comment by avenigalla32** [comment]
Thanks for the feedback!
