### ISSUE TITLE
Peer Review by Cristina Toledo

### ISSUE THREAD

**Issue by ctoledo1** [avenigalla32/Project#5]
Bugs
1. The navigation bar is not the same on every tab. 
2. The pictures of the Jordans are too big and it is hard to see them. 
3. The logo is duplicated by error on the homepage.

Content: 
1. I would suggest making a a contact us page, and an about us page. And have one about Jordans with a dropdown menu for the different types. 
2. You could have a form on a separate page with questions on their favorite type of jordan etc -- not on the homepage.

**Comment by avenigalla32** [comment]
Thanks for the feedback!
